AspNetSamples/AspNetSamples.Mvc/Controllers/SourceController.cs
using AspNetSamples.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace AspNetSamples.Mvc.Controllers
{
    public class SourceController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSourceModel model)
        {
            ModelState.AddModelError("A", "12312312312");
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                var errors = ModelState.ErrorCount;
                foreach (var element in ModelState)
                {
                    if (element.Value.ValidationState == ModelValidationState.Invalid)
                    {
                        var errMsg = element.Key;
                    }
                }
                return View(model);
            }
        }
    }
}

AspNetSamples/AspNetSamples.Mvc/Views/Source/Create.cshtml
@model CreateSourceModel

@{
    var x = 0;
    x++;
}

<h3>Create Source</h3>

<form asp-action="Create" asp-controller="Source" asp-antiforgery="true" method="post">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label class="form-label" asp-for="Name">Name</label>
        <input class="form-control" type="text" asp-for="Name"/>
        <span asp-validation-for="Name"></span>

    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="SourceUrl">SourceUrl</label>
        <input class="form-control" asp-for="SourceUrl"></input>
    </div>

    <div>
        <input type="submit" value="Confirm"/>
    </div>
</form>